apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: dashboard-hpa
spec:
  maxReplicas: 1
  minReplicas: 5
  scaleTargetRef:
    apiVersion:  apps/v1
    kind: Deployment
    name: dashboard-deploy
    targetCPUUtilizationPercentage: 70

